/*
 * This source file was generated by the Gradle 'init' task
 */
package pt.ue.ambiente.client.grpc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ClientAmbienteGrpcUETest {

    @Test
    void testTrueIsTrue() {
        assertTrue(true);
    }
    
}
