/*
 * This source file was generated by the Gradle 'init' task
 */
package pt.ue.ambiente.client.mqtt;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class ClientAmbienteMqttUETest {

    @Test
    void testTrueIsTrue() {
        assertTrue(true);
    }
}
