/*
 * This source file was generated by the Gradle 'init' task
 */
package pt.ue.ambiente.server;

import java.io.IOException;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

import io.grpc.Server;
import io.grpc.ServerBuilder;
import pt.ue.ambiente.server.data.ServerAmbienteDataUE;
import pt.ue.ambiente.server.data.entity.Departamento;
import pt.ue.ambiente.server.data.entity.Dispositivo;
import pt.ue.ambiente.server.data.entity.Edificio;
import pt.ue.ambiente.server.data.entity.Piso;
import pt.ue.ambiente.server.data.entity.Sala;
import pt.ue.ambiente.server.grpc.ServerAmbienteGrpcUE;


@SpringBootApplication
@EnableJpaRepositories(basePackages = "pt.ue.ambiente.server.data.repository")

public class ServerAmbienteUE implements CommandLineRunner {
    private static final Logger log = LoggerFactory.getLogger(ServerAmbienteUE.class);

    private Server grpcServer;

    @Autowired
    private ServerAmbienteGrpcUE grpcServerAmbienteUE;


    @Autowired
    private ServerAmbienteDataUE repositories;


    public static void main(String[] args) {
        SpringApplication.run(ServerAmbienteUE.class, args);
    }

    @Override
    public void run(String... args) {
        try {
            this.startGrpcServer();
            // Keep the application running to listen for gRPC
            this.blockUntilShutdown(); 
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }
    public void startGrpcServer() throws IOException {
        grpcServer = ServerBuilder.forPort(50051)
                .addService(grpcServerAmbienteUE)
                .build()
                .start();

        log.info("===========================================");
        log.info("Servidor gRPC iniciado na porta 50051");
        log.info("===========================================");
        
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            log.info("*** Shutting down gRPC server since JVM is shutting down");
            if (grpcServer != null) {
                grpcServer.shutdown();
            }
            log.info("*** Server shut down");
        }));
    }

    private void blockUntilShutdown() throws InterruptedException {
        if (grpcServer != null) {
            grpcServer.awaitTermination();
        }
    }

    /*
    private static final int PORT = 50051;
    private Server server;

  
    private void start() throws IOException {
        server = ServerBuilder.forPort(PORT)
                .addService(new ServerAmbienteGrpcUE())
                .build()
                .start();

        System.out.println("===========================================");
        System.out.println("Servidor gRPC iniciado na porta " + PORT);
        System.out.println("===========================================");

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.err.println("*** A desligar servidor gRPC devido a shutdown da JVM");
            try {
                ServerAmbienteUE.this.stop();
            } catch (InterruptedException e) {
                e.printStackTrace(System.err);
            }
            System.err.println("*** Servidor desligado");
        }));
    }


    private void stop() throws InterruptedException {
        if (server != null) {
            server.shutdown().awaitTermination();
        }
    }

 
    private void blockUntilShutdown() throws InterruptedException {
        if (server != null) {
            server.awaitTermination();
        }
    }

 
    public static void main(String[] args) {
        final ServerAmbienteUE server = new ServerAmbienteUE();

        try {
            server.start();

            server.blockUntilShutdown();

        } catch (IOException e) {
            System.err.println("Erro ao iniciar o servidor: " + e.getMessage());
            e.printStackTrace();

        } catch (InterruptedException e) {
            System.err.println("Servidor interrompido: " + e.getMessage());
            e.printStackTrace();
        }
    }
    */
}
