/*
 * This source file was generated by the Gradle 'init' task
 */
package pt.ue.ambiente.server;

import pt.ue.ambiente.server.data.entity.Dispositivo;

public class ServerAmbienteUE {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new ServerAmbienteUE().getGreeting());
        
        
    }
}
